### ISSUE TITLE
Configure Strictness

### ISSUE THREAD

**Issue by mouyang** [mockito/mockito-testng#10]
My reason for doing this is outlined [in this issue comment](https://github.com/mockito/mockito-testng/issues/1#issuecomment-489178219).  It's available in `JUnitRule` but not `MockitoTestNGListener`.  At a minimum, strictness should be configurable as a suite parameter.  Overriding the strictness at a lower level is out of scope.

Set in testng.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<suite name="strictness">
  <parameter name="org.mockito.testng.strictness"  value="LENIENT"/>
  <!-- etc. -->
</suite>
```

Set in annotation
```java
@BeforeSuite // or any TestNG annotation for that matter
public void beforeSuite(ITestContext iTestContext) {
  iTestContext.getSuite().getXmlSuite().setParameter("org.mockito.testng.strictness", Strictness.LENIENT);
}
```

**Comment by slawekjaranowski** [comment]
Maybe annotation `MockitoSettings` like in `mockito-junit-jupiter` will be the best.

IHMO extends testng configuration with this information is some complicate.

**Comment by slawekjaranowski** [comment]
I prepared solution with @MockitoSettings annotation.
Example of usage:
```java
@Listeners(MockitoTestNGListener.class)
@MockitoSettings(strictness = Strictness.WARN)
public class StrictnessWarnTest {
 ....
}
```
