### ISSUE TITLE
Migrate to new Shipkit libraries

### ISSUE THREAD

**Issue by slawekjaranowski** [mockito/mockito-testng#14]
similar to https://github.com/mockito/mockito/pull/2069

**Comment by mockitoguy** [comment]
Do you want to take a stab at it?

**Comment by slawekjaranowski** [comment]
It is  new for me, I don't know Shipkit.
After GH actions I will try do something in this case.
But for testing help will be welcome.

**Comment by mockitoguy** [comment]
Ok, give it a shot.

BTW. Do you want to be the maintainer of this project?

**Comment by slawekjaranowski** [comment]
OK, I can take care about project - it seems not to much work - I will be proud.

But return to shipkit ... after last marges new release proces was triggered, but I only see commits in github, there aren't new version on Bintray and Central repository.

As I see we have build both travis .com and .org, so investigating concurrent build on travis is not need when we want to move to GH Action.

**Comment by slawekjaranowski** [comment]
@mockitoguy 

I will need github secrets to be already set.
Are those secrets on organization level, if not please add to this project.

- GH_WRITE_TOKEN
- BINTRAY_API_KEY
- NEXUS_TOKEN_USER
- NEXUS_TOKEN_PWD
