### ISSUE TITLE
Bintray, JCenter - Sunset

### ISSUE THREAD

**Issue by slawekjaranowski** [mockito/mockito-testng#38]
Because of Bintray, JCenter will be  sunset we have to switch publishing from Bintray to OSSRH until February 28th.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

useful link:
 - https://central.sonatype.org/pages/gradle.html

If someone has experience in this topic help will be welcome.

**Comment by slawekjaranowski** [comment]
https://github.com/mockito/mockito/issues/2197

**Comment by slawekjaranowski** [comment]
https://github.com/gradle-nexus/publish-plugin

**Comment by slawekjaranowski** [comment]
@mockitoguy 
I will need GitHub Action secrets PGP_KEY and PGP_PWD with proper value for Mockito organisation.
Maybe you have such values for GitHub organisation so you can enable it for this repository.

**Comment by mockitoguy** [comment]
@slawekjaranowski, sure, I'll expose them to this repo.
